version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      DOCKER_ENV: 'true' # This triggers Docker mode
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodapp
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: foodpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
  backend:
    build: .
    container_name: food-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/app  
      - /app/node_modules  

volumes:
  mysql-data:
